[workspace]
resolver = "2"
members = ["client", "goals", "pathfind", "utils"]
exclude = ["./azalea", "./azalea/*"]

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
azalea.path = "./azalea/azalea"
utils.path = "./utils"
pathfind.path = "./pathfind"
