[workspace]
resolver = "2"
members = ["client", "utils"]

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
utils.path = "./utils"

azalea = { git = "https://github.com/azalea-rs/azalea", rev = "6a83a6f" }
