[package]
name = "honeypack"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["net"] }
